{% set name = "plotext" %}
{% set version = "6.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/plotext-{{ version }}.tar.gz
  sha256: d49792c1881a15dfe27a23b1d659660d3962f9e1afaac21250eccc3bbd47581f

build:
  number: 0
  script:
    # resolve CXX path with command -v
    - CXX_PATH="$(command -v "${CXX}")"  # [not win]
    # symlink it to g++ in the build bin dir
    - ln -sf "${CXX_PATH}" "${BUILD_PREFIX}/bin/g++"  # [not win]
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plotext = plotext._cli:main

requirements:
  build:
    - {{ stdlib("c") }}  # [not win]
    - {{ compiler("c") }}  # [not win]
    - {{ compiler("cxx") }}  # [not win]
    - {{ stdlib("m2w64_c") }} # [win]
    - {{ compiler("m2w64_c") }} # [win]
    - {{ compiler("m2w64_cxx") }} # [win]
  host:
    - pip
    - python
    - setuptools >=64
    - wheel
  run:
    - python

test:
  imports:
    - plotext
  requires:
    - pip
    - python
  commands:
    - pip check
    - plotext --help

about:
  home: https://github.com/piccolomo/plotext
  summary: plotext plots data directly on terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
