{% set name = "plotext" %}
{% set version = "6.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/plotext-{{ version }}.tar.gz
  sha256: 6b729ce6376c5c1c2152fe85e0449dcc54879d0923b3c6c8d1670108245c6f84

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plotext = plotext.plotext_cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - plotext
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - plotext --help

about:
  home: https://github.com/piccolomo/plotext
  summary: plotext plots data directly on terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
